# --- Builder Stage ---
FROM node:18-alpine AS build 

WORKDIR /app
COPY package*.json .
RUN npm install --frozen-lockfile 
COPY . .
RUN npm run build

# --- Final Stage --- 
FROM nginx:stable-alpine-slim AS prod
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY  nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000 
CMD ["nginx", "-g", "daemon off;"]
