# --- Builder Stage ---
FROM python:3.11-slim AS build

RUN pip install poetry==1.4.2
WORKDIR /app
COPY pyproject.toml poetry.lock ./ 
RUN poetry config virtualenvs.in-project true && poetry install --no-root
COPY . .

# --- Final Stage ---
FROM python:3.11-slim
WORKDIR /app
RUN pip install poetry==1.4.2
COPY --from=build /app /app
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH=/app
EXPOSE 8000
RUN chmod +x ./prestart.sh
CMD ["bash", "-c", "poetry run ./prestart.sh && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"]
