# --- Builder Stage ---
FROM python:3.11-slim AS build

RUN pip install poetry==1.4.2
WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.in-project true && poetry install --no-root
COPY . .

# --- Final Stage ---
FROM python:3.11-slim
WORKDIR /app
COPY --from=build /app /app
ENV PATH="/app/.venv/bin:$PATH"
EXPOSE 8000
CMD ["bash", "-c", "poetry run ./prestart.sh && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"]
